# Generated by Django 5.2.13 on 2026-08-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='donations/'),
        ),
    ]
