# Generated by Django 5.2.13 on 2026-08-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puja', '0002_donation_receipt_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='material_description',
            field=models.CharField(blank=True, help_text='e.g. 50kg Rice, 20kg Potato', max_length=255, null=True),
        ),
    ]
