# Generated by Django 5.2.13 on 2026-08-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puja', '0003_donation_material_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PujaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_year_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Previous Year Carry Forward Balance')),
            ],
        ),
    ]
