# Generated by Django 5.2.13 on 2026-08-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puja', '0004_pujaconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='house_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='House Number / Address'),
        ),
    ]
