# Generated by Django 5.2.13 on 2026-08-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puja', '0006_alter_donation_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='house_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='House Holder Name'),
        ),
    ]
