# Generated by Django 5.2.13 on 2026-08-29 13:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puja', '0007_alter_donation_house_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='house_number',
        ),
        migrations.CreateModel(
            name='HouseDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100, verbose_name='House Holder Name')),
                ('house_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='House Number / Details')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
