# Generated by Django 5.2.13 on 2026-09-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puja', '0009_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['order_index', 'date_received', 'id']},
        ),
        migrations.AddField(
            model_name='donation',
            name='order_index',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Display Order'),
        ),
    ]
