# Generated by Django 5.2.13 on 2026-09-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puja', '0010_alter_donation_options_donation_order_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['order_index', 'date_incurred', 'id']},
        ),
        migrations.AddField(
            model_name='expense',
            name='order_index',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Display Order'),
        ),
    ]
